//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20190507_demotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class top3quate
    {
        public string bookName { get; set; }
        public int topID { get; set; }
        public Nullable<int> totVote { get; set; }
    }
}
